name: PHPUnit Tests

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        php_ver:
          - "7.4"
        wp_ver:
          - "latest"
        wc_ver:
          - "latest"
          - "5.6.0"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          version: 2

      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      - name: Run install-wp-tests.sh
        run: ./vendor/bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wp_ver }}

      - name: Run install-woocommerce.sh
        run: sudo ./tests/bin/install-woocommerce.sh ${{ matrix.wc_ver }}

      - name: Run phpunit
        run: ./vendor/bin/phpunit -c phpunit.xml
        env:
          WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
          WC_VERSION: ${{ matrix.wc_ver }}
